services:
  mongodb:
    image: mongo:4.2.24
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--bind_ip_all"]
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/simplebalance
      WEB_FLUX_APP_CLIENT_ID: ${WEB_FLUX_APP_CLIENT_ID}
      WEB_FLUX_APP_CLIENT_SECRET: ${WEB_FLUX_APP_CLIENT_SECRET}
      WEB_FLUX_APP_ISSUER_URL: ${WEB_FLUX_APP_ISSUER_URL}
      JWKS_URL: ${JWKS_URL}
      ISSUER_URL: ${ISSUER_URL}

volumes:
  mongo_data:
