server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: "SimpleBalanceWebFlux"
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/simplebalance}
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          web-flux-app:
            client-id: ${CLIENT_ID:web-flux-app}
            client-secret: ${CLIENT_SECRET:123456789}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,read
        provider:
          web-flux-app:
            issuer-uri: ${ISSUER_URL:http://localhost:9000}
      resourceserver:
        jwt:
          jwk-set-uri: ${JWKS_URL:http://localhost:9000/oauth2/jwks}
          issuer-uri: ${ISSUER_URL:http://localhost:9000}

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    org.springframework.web.reactive.function.client: WARN

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"